sudo: required
language: node_js
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "git submodule update --init --recursive"
  - "phantomjs --webdriver=9515 &"
node_js:
  - "6.0.0"
install:
  - "curl https://install.meteor.com | /bin/sh"
  - "nvm install stable"
  - "nvm use stable"
  - "npm install -g gagarin"
services:
  - mongodb
script:
  - gagarin -v
notifications:
  slack: lille:CUlWQvK55OmTyg7Uqs8HQuAI
